# Generated by Django 4.2.4 on 2024-05-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_selectcandidatejob_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
    ]
